// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Showcase.Persistence;

namespace Showcase.Persistence.Migrations
{
    [DbContext(typeof(ShowcaseDbContext))]
    partial class ShowcaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Showcase.Domain.Entities.DisplayProject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("text");

                    b.Property<int[]>("Languages")
                        .HasColumnName("languages")
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("SourceCodeUrl")
                        .HasColumnName("source_code_url")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnName("thumbnail_url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("display_projects");
                });
#pragma warning restore 612, 618
        }
    }
}
